a = input('Digite algo')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ' , a.isspace())
print('É numérico? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em Maiusculas? ', a.isupper())
print('Está em minusculas? ', a.islower())
print('Está capitalizado?',a.istitle())