print('Por favor digite a data do seu aniversário abaixo!')
dia = input('Dia = ')
mes = input('Mês = ')
ano = input('Ano = ')
print('Você nasceu no dia ' + dia + ' de ' + mes + ' de ' + ano + '. Correto?')
